[tool.poetry]
name = "sticker-finder"
version = "1.0.0"
description = "A telegram bot for searching all the stickers (just like @gif)."
authors = ["Arne Beer <contact@arne.beer>"]
license = "MIT"
repository = "https://github.com/nukesor/sticker-finder"

[tool.poetry.dependencies]
python = ">=3.6"
raven = "6.10"
alembic = "1.0"
python-telegram-bot = "^12.1"
SQLAlchemy = "^1.3"
sqlalchemy-utils = "^0.34"
psycopg2-binary = "^2.8"
pytesseract = "^0.2"
imutils = "^0.5"
toml = "^0.10"

matplotlib = "3.1"
pandas = "^0.24"
pillow = "^6.0"

[tool.poetry.dev-dependencies]
pytest-mock = "^1.10"
pytest = "^4.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
