[telegram]
api_key = "697193300:AAGQ5sH1DCxYu6Bf5398k9miL7EscTHwYyo"
worker_count = 20
admin = "Nukesor"
bot_name = "stickerfinder"

[database]
sql_uri = "postgres://localhost/stickerfinder_test"
connection_count = 20
overflow_count = 10

[logging]
sentry_enabled = false
sentry_token = "https://85ffca5aa9384619ba1ef254bc10828a@sentry.io/1286711"
log_level = 20
debug = false

[webhook]
enabled = false
domain = "https://localhost"
token = "std_bot"
cert_path = "/path/to/cert.pem"
port = 7000

[job]
user_check_count = 200
report_count = 10

[mode]
leecher = false
